### ISSUE TITLE
DOS file endings do not work

### ISSUE THREAD

**Issue by blakemcbride** [cwfoo/emacs-batch-indent#2]
Greetings,

I tried processing a Scheme file that was formatted with DOS line endings (CRLF).  Your program added a blank line after every input line.  I converted the file to standard Unix file-ending (LF) and it worked as expected.  I am on a Linux box.

Thanks.

Blake

**Comment by blakemcbride** [comment]
I wrote a program to translate between the two different line-endings.  It's probably best if you can get your code to work without it, otherwise, it's at [](https://github.com/blakemcbride/Fix-line-endings)

**Comment by cwfoo** [comment]
Thank you for the bug report. Problem fixed in 9050e81c7dde2e6db1325e20bdea1f35284f97c3.
